<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="styles/styles.css">
        <meta charset="UTF-8">
        <meta name="description" content="Job Details page of our cybersecurity company">
        <meta name="keywords" content="cybersecurity, security, IT, protection">
        <meta name="author" content="Quantum Shield's website developers">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Job Application Page</title>
    </head>

    <body>
        <!-- Company Logo and Navigation Bar  -->
        <header>
            <img src="images/Quantum_Shield_Logo.png" alt="Quantum Shield Logo" class="logo">
    
            